name: Register Cluster to Nirmata

on:
 workflow_dispatch
#   push:
#     branches:
#     - main

env:
  EKS_CLUSTER: NirmataTest
  EKS_REGION: us-east-1

jobs:
  Job1:
    name: Register Nirmata Cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    ## AWS Credentials
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.EKS_REGION }}

    # Get the EKS credentials so we can deploy to the cluster
    - run: |-
        aws eks --region $EKS_REGION update-kubeconfig --name $EKS_CLUSTER
       
        
        
   
   # Register Cluster in Nirmata
    - name: Install nctl command line
      run: |-
       curl -LO https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_3.2.3/nctl_3.2.3_linux_64-bit.zip
       unzip nctl_3.2.3_linux_64-bit.zip
       chmod 755 nctl
       mv nctl /usr/local/bin/
   # nctl Login    
    - name: Login with Token
      run: |-
       nctl clusters get --token "${{ secrets.NIRMATA_TOKEN }}"


    - name: Register Cluster
      run: |-
       cluster-namespace = $(kubectl config get-contexts --no-headers | awk '{ print $2 }')
       nctl cluster register  "'${cluster-namespace}'" -f /home/runner/.kube/config -t default-addons-type -n nirmatatest --token "${{ secrets.NIRMATA_TOKEN }}"
       

